#!/usr/bin/env python3
import json
import time
from pathlib import Path

import numpy as np
import soundfile as sf
from kokoro import KPipeline

ROOT = Path(__file__).resolve().parent.parent
text = (ROOT / 'assets' / 'test_sentence_fr.txt').read_text(encoding='utf-8').strip()
out_wav = ROOT / 'audio' / 'kokoro_fr.wav'
out_json = ROOT / 'logs' / 'kokoro_metrics.json'

start = time.perf_counter()
pipeline = KPipeline(lang_code='f')
init_done = time.perf_counter()

first_chunk_time = None
chunks = []
for _graphemes, _phonemes, audio in pipeline(text, voice='ff_siwis'):
    if first_chunk_time is None:
        first_chunk_time = time.perf_counter()
    chunks.append(audio)

end = time.perf_counter()
if not chunks:
    raise RuntimeError('No audio chunks generated by Kokoro')

wav = np.concatenate(chunks).astype(np.float32)
sf.write(str(out_wav), wav, 24000)

metrics = {
    'text': text,
    'init_seconds': init_done - start,
    'first_chunk_seconds': (first_chunk_time - start) if first_chunk_time else None,
    'generation_seconds': end - init_done,
    'total_seconds': end - start,
    'samples': int(wav.shape[0]),
    'sample_rate': 24000,
    'voice': 'ff_siwis',
}
out_json.write_text(json.dumps(metrics, indent=2, ensure_ascii=False), encoding='utf-8')
print(json.dumps(metrics, ensure_ascii=False))
